// This file is automatically generated.

import type { BlockConfig } from "./_types"

import acacia_log from "./acacia_log.json"
import amethyst_block from "./amethyst_block.json"
import amethyst_cluster from "./amethyst_cluster.json"
import ancient_debris from "./ancient_debris.json"
import birch_log from "./birch_log.json"
import cherry_log from "./cherry_log.json"
import coal_ore from "./coal_ore.json"
import copper_ore from "./copper_ore.json"
import crimson_stem from "./crimson_stem.json"
import dark_oak_log from "./dark_oak_log.json"
import deepslate from "./deepslate.json"
import deepslate_coal_ore from "./deepslate_coal_ore.json"
import deepslate_copper_ore from "./deepslate_copper_ore.json"
import deepslate_diamond_ore from "./deepslate_diamond_ore.json"
import deepslate_emerald_ore from "./deepslate_emerald_ore.json"
import deepslate_gold_ore from "./deepslate_gold_ore.json"
import deepslate_iron_ore from "./deepslate_iron_ore.json"
import deepslate_lapis_ore from "./deepslate_lapis_ore.json"
import deepslate_redstone_ore from "./deepslate_redstone_ore.json"
import diamond_ore from "./diamond_ore.json"
import emerald_ore from "./emerald_ore.json"
import gold_ore from "./gold_ore.json"
import iron_ore from "./iron_ore.json"
import jungle_log from "./jungle_log.json"
import lapis_ore from "./lapis_ore.json"
import mangrove_log from "./mangrove_log.json"
import nether_gold_ore from "./nether_gold_ore.json"
import oak_log from "./oak_log.json"
import obsidian from "./obsidian.json"
import quartz_ore from "./quartz_ore.json"
import redstone_ore from "./redstone_ore.json"
import spruce_log from "./spruce_log.json"
import stone from "./stone.json"
import warped_stem from "./warped_stem.json"

export default {
  "minecraft:acacia_log": acacia_log,
  "minecraft:amethyst_block": amethyst_block,
  "minecraft:amethyst_cluster": amethyst_cluster,
  "minecraft:ancient_debris": ancient_debris,
  "minecraft:birch_log": birch_log,
  "minecraft:cherry_log": cherry_log,
  "minecraft:coal_ore": coal_ore,
  "minecraft:copper_ore": copper_ore,
  "minecraft:crimson_stem": crimson_stem,
  "minecraft:dark_oak_log": dark_oak_log,
  "minecraft:deepslate": deepslate,
  "minecraft:deepslate_coal_ore": deepslate_coal_ore,
  "minecraft:deepslate_copper_ore": deepslate_copper_ore,
  "minecraft:deepslate_diamond_ore": deepslate_diamond_ore,
  "minecraft:deepslate_emerald_ore": deepslate_emerald_ore,
  "minecraft:deepslate_gold_ore": deepslate_gold_ore,
  "minecraft:deepslate_iron_ore": deepslate_iron_ore,
  "minecraft:deepslate_lapis_ore": deepslate_lapis_ore,
  "minecraft:deepslate_redstone_ore": deepslate_redstone_ore,
  "minecraft:diamond_ore": diamond_ore,
  "minecraft:emerald_ore": emerald_ore,
  "minecraft:gold_ore": gold_ore,
  "minecraft:iron_ore": iron_ore,
  "minecraft:jungle_log": jungle_log,
  "minecraft:lapis_ore": lapis_ore,
  "minecraft:mangrove_log": mangrove_log,
  "minecraft:nether_gold_ore": nether_gold_ore,
  "minecraft:oak_log": oak_log,
  "minecraft:obsidian": obsidian,
  "minecraft:quartz_ore": quartz_ore,
  "minecraft:redstone_ore": redstone_ore,
  "minecraft:spruce_log": spruce_log,
  "minecraft:stone": stone,
  "minecraft:warped_stem": warped_stem,
} as Record<string, BlockConfig>
