// This file is automatically generated.
import acaciaLog from "./acacia_log.json"
import amethystBlock from "./amethyst_block.json"
import amethystCluster from "./amethyst_cluster.json"
import ancientDebris from "./ancient_debris.json"
import birchLog from "./birch_log.json"
import cherryLog from "./cherry_log.json"
import coalOre from "./coal_ore.json"
import copperOre from "./copper_ore.json"
import crimsonStem from "./crimson_stem.json"
import darkOakLog from "./dark_oak_log.json"
import deepslate from "./deepslate.json"
import deepslateCoalOre from "./deepslate_coal_ore.json"
import deepslateCopperOre from "./deepslate_copper_ore.json"
import deepslateDiamondOre from "./deepslate_diamond_ore.json"
import deepslateEmeraldOre from "./deepslate_emerald_ore.json"
import deepslateGoldOre from "./deepslate_gold_ore.json"
import deepslateIronOre from "./deepslate_iron_ore.json"
import deepslateLapisOre from "./deepslate_lapis_ore.json"
import deepslateRedstoneOre from "./deepslate_redstone_ore.json"
import diamondOre from "./diamond_ore.json"
import emeraldOre from "./emerald_ore.json"
import goldOre from "./gold_ore.json"
import ironOre from "./iron_ore.json"
import jungleLog from "./jungle_log.json"
import lapisOre from "./lapis_ore.json"
import mangroveLog from "./mangrove_log.json"
import netherGoldOre from "./nether_gold_ore.json"
import oakLog from "./oak_log.json"
import obsidian from "./obsidian.json"
import quartzOre from "./quartz_ore.json"
import redstoneOre from "./redstone_ore.json"
import spruceLog from "./spruce_log.json"
import stone from "./stone.json"
import type { BlockConfig } from "./types"
import warpedStem from "./warped_stem.json"

export default {
  acacia_log: acaciaLog,
  amethyst_block: amethystBlock,
  amethyst_cluster: amethystCluster,
  ancient_debris: ancientDebris,
  birch_log: birchLog,
  cherry_log: cherryLog,
  coal_ore: coalOre,
  copper_ore: copperOre,
  crimson_stem: crimsonStem,
  dark_oak_log: darkOakLog,
  deepslate: deepslate,
  deepslate_coal_ore: deepslateCoalOre,
  deepslate_copper_ore: deepslateCopperOre,
  deepslate_diamond_ore: deepslateDiamondOre,
  deepslate_emerald_ore: deepslateEmeraldOre,
  deepslate_gold_ore: deepslateGoldOre,
  deepslate_iron_ore: deepslateIronOre,
  deepslate_lapis_ore: deepslateLapisOre,
  deepslate_redstone_ore: deepslateRedstoneOre,
  diamond_ore: diamondOre,
  emerald_ore: emeraldOre,
  gold_ore: goldOre,
  iron_ore: ironOre,
  jungle_log: jungleLog,
  lapis_ore: lapisOre,
  mangrove_log: mangroveLog,
  nether_gold_ore: netherGoldOre,
  oak_log: oakLog,
  obsidian: obsidian,
  quartz_ore: quartzOre,
  redstone_ore: redstoneOre,
  spruce_log: spruceLog,
  stone: stone,
  warped_stem: warpedStem,
} as Record<string, BlockConfig>
