name: Bundle and Push

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
          
      - name: Install dependencies
        run: npm install
        
      - name: Bundle project
        run: gulp
        
      - name: Push to dist branch
        run: |
          git config --global user.name "Automated"
          git config --global user.email "actions@users.noreply.github.com"
          git checkout -b dist
          git add -f dist/
          git commit -m "Auto-push dist folder"
          git push origin dist