name: Bundle and Push

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
        
      - name: Clone repository
        run: |
          git clone -b main ${{ github.repositoryUrl }} main
          cd main
        
      - name: Install dependencies
        run: npm install
        
      - name: Clone dist branch
        run: git clone -b dist ${{ github.repositoryUrl }} dist
        
      - name: Bundle project
        run: gulp
        
      - name: Push to dist branch
        run: |
          cd dist
          git config --global user.name "Automated"
          git config --global user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Auto-push dist"
          git push origin dist